# Generated by Django 4.1.5 on 2023-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_condidate_max_salary_condidate_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidate',
            name='Country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='condidate',
            name='Exprience',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='condidate',
            name='Jobdescription',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='condidate',
            name='Shift',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='condidate',
            name='Website',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='condidate',
            name='highest_edu',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='condidate',
            name='job_type',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
