# Generated by Django 4.1.5 on 2023-01-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_condidate_job_cotegory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
