# Generated by Django 4.1.5 on 2023-01-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_name', models.CharField(max_length=150)),
                ('Company_name', models.CharField(max_length=150)),
                ('Company_address', models.CharField(max_length=250)),
                ('Job_description', models.TextField(max_length=500)),
                ('Qualification', models.CharField(max_length=250)),
                ('Responsibilities', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=250)),
                ('Company_website', models.CharField(max_length=150)),
                ('Company_email', models.CharField(max_length=150)),
                ('Company_contact', models.CharField(max_length=20)),
                ('Salary_package', models.CharField(max_length=250)),
                ('Experience', models.IntegerField()),
                ('Comapany_logo', models.ImageField(upload_to='myapp/img/company')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
        ),
    ]
