# Generated by Django 4.1.5 on 2023-01-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_jobdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=150)),
                ('Min_salary', models.CharField(max_length=100)),
                ('Max_salary', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Resume', models.FileField(upload_to='app/resume')),
                ('Condidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.condidate')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobdetail')),
            ],
        ),
    ]
